INSERT INTO USERS (USER_ID, NAME, LASTNAME, PASSWORD , EMAIL,GENDER,TELEPHONE) VALUES (1,'PHEEHLARM', 'PHEERAPHON', 'RICKYLNWZA', 'PHEEHLAEM@GMAIL.COM', 'MALE', '0123456789');

INSERT INTO TEACHER (TEACHER_ID,NAME,LASTNAME) VALUES (1,'ADAM','SMITH');

INSERT INTO COURSE (COURSE_ID,NAME,PRICE,TEACHER_ID) VALUES (1,'Unity101',190,1);
INSERT INTO COURSE (COURSE_ID,NAME,PRICE,TEACHER_ID) VALUES (2,'Python101',250,1);
INSERT INTO COURSE (COURSE_ID,NAME,PRICE,TEACHER_ID) VALUES (3,'Photoshop101',500,1);
INSERT INTO COURSE (COURSE_ID,NAME,PRICE,TEACHER_ID) VALUES (4,'HowToBeCat',150,1);

INSERT INTO BOOKCOURSE (BOOKCOURSE_ID,USER_ID,COURSE_ID,DATETIME) VALUES (1,1,1,'15,07,2022');
INSERT INTO BOOKCOURSE (BOOKCOURSE_ID,USER_ID,COURSE_ID,DATETIME) VALUES (2,1,4,'16,07,2022');